In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from tqdm import tqdm_notebook as tqdm
%matplotlib inline
%load_ext line_profiler

In [2]:
# os.listdir('../../data/')

In [2]:
train_df = pd.read_csv('../../data/train.csv')
structure_df = pd.read_csv('../../data/structures.csv')

In [3]:
# train_df.head()


In [3]:
info = pd.read_pickle('../../pkl/atom_info.pkl')

In [4]:
# info

In [5]:
# info["dsgdb9nsd_000001"]

In [13]:
def add_atomic_x():
    a = np.zeros((len(train_df),2),dtype=np.float32)
    for i,row in tqdm(train_df.iterrows(),total=len(train_df)):
        a[i,0] = info[row[1]][row[2]]["x"]
        a[i,1] = info[row[1]][row[3]]["x"]
    return a

In [16]:
def add_atomic_y():
    a = np.zeros((len(train_df),2),dtype=np.float32)
    for i,row in tqdm(train_df.iterrows(),total=len(train_df)):
        a[i,0] = info[row[1]][row[2]]["y"]
        a[i,1] = info[row[1]][row[3]]["y"]
    return a

In [18]:
def add_atomic_z():
    a = np.zeros((len(train_df),2),dtype=np.float32)
    for i,row in tqdm(train_df.iterrows(),total=len(train_df)):
        a[i,0] = info[row[1]][row[2]]["z"]
        a[i,1] = info[row[1]][row[3]]["z"]
    return a

In [20]:
def add_atomic_gyromagnetic_ratio():
    a = np.zeros((len(train_df),2),dtype=np.float32)
    for i,row in tqdm(train_df.iterrows(),total=len(train_df)):
        a[i,0] = info[row[1]][row[2]]["gyromagnetic_ratio"]
        a[i,1] = info[row[1]][row[3]]["gyromagnetic_ratio"]
    return a

In [14]:
atomic_x = add_atomic_x()

In [17]:
atomic_y = add_atomic_y()

In [19]:
atomic_z = add_atomic_z()

In [22]:
atomic_ratio = add_atomic_gyromagnetic_ratio()

In [28]:
# pd.to_pickle(atomic_x, '../../pkl/atomic_x.pkl')

In [29]:
# pd.to_pickle(atomic_y, '../../pkl/atomic_y.pkl')

In [30]:
# pd.to_pickle(atomic_z, '../../pkl/atomic_z.pkl')

In [31]:
# pd.to_pickle(atomic_ratio , '../../pkl/atomic_ratio.pkl')

In [6]:
x = pd.read_pickle('../../pkl/atomic_x.pkl')

In [7]:
y = pd.read_pickle('../../pkl/atomic_y.pkl')

In [8]:
z = pd.read_pickle('../../pkl/atomic_z.pkl')

In [9]:
x


array([[1.2607453, 0.8166945],
       [1.2607453, 1.2607453],
       [1.2607453, 1.2607453],
       ...,
       [1.2607453, 0.8166945],
       [1.2607453, 0.8166945],
       [1.2607453, 0.8166945]], dtype=float32)

In [10]:
y

array([[-1.2467537, -0.8130668],
       [-1.2467537, -1.2467537],
       [-1.2467537, -1.2467537],
       ...,
       [-1.2467537, -0.8130668],
       [-1.2467537, -0.8130668],
       [-1.2467537, -0.8130668]], dtype=float32)

In [11]:
z

array([[42.57748, 10.705  ],
       [42.57748, 42.57748],
       [42.57748, 42.57748],
       ...,
       [42.57748, 10.705  ],
       [42.57748, 10.705  ],
       [42.57748, 10.705  ]], dtype=float32)

In [56]:
# np.arctan((y.T[0][0])/(x.T[0][0]))

-0.77981836

In [60]:
# #xy平面でのx軸とのなす角
# angle = np.zeros((len(x),2),dtype=np.float32)
# angle_diff = np.zeros((len(x),1),dtype=np.float32)
# for i in tqdm(range(len(x))):
#     #atom0
#     angle[i,0] = np.arctan(y[i][0]/x[i][0])
#     #atom1
#     angle[i,1] = np.arctan(y[i][1]/x[i][1])
#     angle_diff[i,0] = np.abs(angle[i,1]-angle[i,0])

In [61]:
# angle

array([[-0.77981836, -0.78317225],
       [-0.77981836, -0.77981836],
       [-0.77981836, -0.77981836],
       ...,
       [-0.77981836, -0.78317225],
       [-0.77981836, -0.78317225],
       [-0.77981836, -0.78317225]], dtype=float32)

In [65]:
# angle_diff.shape

(4658147, 1)

In [63]:
# pd.to_pickle(angle , '../../pkl/angle.pkl')

In [64]:
# pd.to_pickle(angle_diff , '../../pkl/angle_diff.pkl')

In [18]:
#２原子間のxの差
x_diff = np.zeros((len(x),1),dtype=np.float32)
for i in tqdm(range(len(x))):
    x_diff[i,0] = np.abs(x[i][0] - x[i][1])

In [19]:
#２原子間のyの差
y_diff = np.zeros((len(x),1),dtype=np.float32)
for i in tqdm(range(len(x))):
    y_diff[i,0] = np.abs(y[i][0] - y[i][1])

In [20]:
#２原子間のzの差
z_diff = np.zeros((len(x),1),dtype=np.float32)
for i in tqdm(range(len(x))):
    z_diff[i,0] = np.abs(z[i][0] - z[i][1])

In [27]:
# pd.to_pickle(x_diff , '../../pkl/x_diff.pkl')

In [28]:
# pd.to_pickle(y_diff , '../../pkl/y_diff.pkl')

In [29]:
# pd.to_pickle(z_diff , '../../pkl/z_diff.pkl')

In [7]:
num = pd.read_pickle('../../pkl/each_atom_num.pkl')

In [53]:
num.shape

(130775, 5)

In [4]:
m_name = structure_df["molecule_name"].unique()

In [5]:
df1 = pd.DataFrame(m_name,columns = ["molecule_name"])

In [8]:
df2 = pd.DataFrame(num,columns = ["C","H","N","O","F"])

In [10]:
new_df = pd.concat([df1,df2],axis = 1)

In [11]:
new_df.head()

molecule_name  C  H  N  O  F
0  dsgdb9nsd_000001  1  4  0  0  0
1  dsgdb9nsd_000002  0  3  1  0  0
2  dsgdb9nsd_000003  0  2  0  1  0
3  dsgdb9nsd_000004  2  2  0  0  0
4  dsgdb9nsd_000005  1  1  1  0  0

In [21]:
def atom_num():
    a = np.zeros((len(train_df),5),dtype=np.float32)
    stock = None
    molecule_name_atom = None
    for i,row in tqdm(train_df.iterrows(),total=len(train_df)):
        
        if stock != row[1]:
            stock = row[1]
            molecule_name_atom = new_df[new_df['molecule_name']==stock].values
        a[i,0] = molecule_name_atom[0][1]
        a[i,1] = molecule_name_atom[0][2]
        a[i,2] = molecule_name_atom[0][3]
        a[i,3] = molecule_name_atom[0][4]
        a[i,4] = molecule_name_atom[0][5]
        
    return a
    

In [22]:
ato = atom_num()

In [25]:
ato.shape

(4658147, 5)

In [26]:
# pd.to_pickle(ato, '../../pkl/atom_num.pkl')

In [20]:
# %lprun  -f atom_num atom_num()